declare function createTestStudent(): Promise<{
    id: string;
    email: string;
    verified: boolean;
    tags: string[];
    passwordHash: string;
    firstName: string;
    lastName: string;
    schoolName: string;
    major: string | null;
    bio: string | null;
    profilePhoto: string | null;
    registrationStatus: string;
    registrationPaid: boolean;
    fundingGoal: import("@prisma/client/runtime/library").Decimal;
    amountRaised: import("@prisma/client/runtime/library").Decimal;
    totalDonations: number;
    donationGoal: import("@prisma/client/runtime/library").Decimal | null;
    profileUrl: string;
    isActive: boolean;
    graduationYear: string | null;
    location: string | null;
    urgency: string;
    lastActive: Date;
    publicProfile: boolean;
    allowMessages: boolean;
    showDonorNames: boolean;
    createdAt: Date;
    updatedAt: Date;
    schoolRelationId: string | null;
    schoolVerified: boolean;
    studentIdVerified: boolean;
    userId: string;
    welcomeBoxStatus: string;
    gpa: import("@prisma/client/runtime/library").Decimal | null;
    achievements: string | null;
    financialNeed: string | null;
    phoneNumber: string | null;
    linkedinUrl: string | null;
    personalStatement: string | null;
    verifiedAt: Date | null;
    verifiedBy: string | null;
    rejectedAt: Date | null;
    rejectedBy: string | null;
    rejectionReason: string | null;
    paymentStatus: string | null;
    paymentComplete: boolean;
    paymentIntentId: string | null;
    paymentCompletedAt: Date | null;
    registrationFee: number | null;
}>;
export { createTestStudent };
//# sourceMappingURL=create-test-student.d.ts.map