apiVersion: apps/v1
kind: Deployment
metadata:
  name: village-backend
  namespace: default
  labels:
    app: village-backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: village-backend
  template:
    metadata:
      labels:
        app: village-backend
        version: v1
    spec:
      containers:
      - name: backend
        image: 898307279366.dkr.ecr.us-east-1.amazonaws.com/village-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: village-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: village-secrets
              key: jwt-secret
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: village-secrets
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: village-secrets
              key: aws-secret-access-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: village-backend-service
  namespace: default
  labels:
    app: village-backend
spec:
  selector:
    app: village-backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP